version: "3.4"

services:
    db:
        image: postgres
        environment:
            PG_HOST: db
            POSTGRES_DB: mariaquiteria
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./db:/var/lib/postgresql

    web:
        build:
            context: .
            target: dev
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file: .env
        depends_on:
            - db
