version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"

    web:
        build: .
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file: .env
        depends_on:
            - db
