version: "3.4"

services:
    db:
        image: library/postgres:12.4
        environment:
            POSTGRES_DB: mariaquiteria
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./db:/var/lib/postgresql

    tika:
        image: apache/tika
        ports:
            - "9998:9998"

    rabbitmq:
        image: rabbitmq
        ports:
          - "5672:5672"
        restart: always

    dramatiq:
        build:
            context: .
            dockerfile: dramatiq.Dockerfile
        environment:
            DATABASE_HOST: db
            TIKA_CLIENT_ONLY: 1
            TIKA_SERVER_ENDPOINT: http://tika:9998
        depends_on:
            - db
            - rabbitmq
            - tika

    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        environment:
            DATABASE_HOST: db
        env_file: .env
        depends_on:
            - db
            - dramatiq
