version: "3.4"

services:
    db:
        image: library/postgres:11-alpine
        environment:
            POSTGRES_DB: mariaquiteria
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./db:/var/lib/postgresql

    rabbitmq:
        image: rabbitmq
        ports:
          - "5672:5672"
          - "15672:15672"
        healthcheck:
          test: [ "CMD", "nc", "-z", "localhost", "5672" ]
          interval: 5s
          timeout: 15s
          retries: 1

    tika:
        image: apache/tika
        ports:
            - "9998:9998"

    web:
        build: .
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        environment:
            DATABASE_HOST: db
        env_file: .env
        depends_on:
            - db
            - worker

    worker:
        build: .
        command: ["celery", "-A", "web", "worker", "-l", "INFO", "--without-heartbeat", "--without-gossip", "--without-mingle"]
        environment:
            DATABASE_HOST: db
            TIKA_CLIENT_ONLY: 1
            TIKA_SERVER_ENDPOINT: http://tika:9998
        env_file: .env
        restart: on-failure
        depends_on:
            - tika
            - db
            - rabbitmq
