name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
      - name: Lint
        run: |
          black --check .
          flake8 .
      - name: Check migrations
        env:
          DJANGO_SETTINGS_MODULE: "web.settings"
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/mariaquiteria"
        run: python manage.py makemigrations --check
      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: "web.settings"
          DJANGO_CONFIGURATION: "Dev"
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/mariaquiteria"
        run: |
          python manage.py collectstatic
          pytest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mariaquiteria
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  deploy:
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - name: Push to dokku
        uses: dokku/github-action@master
        env:
          branch: main
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_remote_url: ${{ secrets.DOKKU_REMOTE_URL }}

    needs: [build]
