name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
      - name: Lint
        run: |
          black --check .
          flake8 .

      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: "core.settings"
          DJANGO_CONFIGURATION: "Dev"
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
        run: |
          python manage.py collectstatic
          pytest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
