name: "Pipeline para build de imagem docker"
on:
  push: 
  release:
    types: [created]
jobs:
  docker:
    uses: "mentoriaiac/cicd_centralizado/.github/workflows/docker_build.yaml@docker/v1"
    with:
      image: wf975621/mariaqueteria

      push_image: ${{github.event_name == 'release'}}
    secrets:
      docker_user: ${{secrets.DOCKER_LOGIN}}
      docker_password: ${{secrets.TOKEN_DOCKERHUB}}